### ISSUE TITLE
Uploading sdp.json does not work

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean-vpn#17]
I get following

```
lethe@nl01:~$ python3 /opt/itns/bin/itnsdispatcher --upload-sdp
WARNING:root:Uploading SDP to server https://slsf2fy3eb.execute-api.us-east-1.amazonaws.com/qa/v1
INFO:audit:UPLOAD,SDP,/opt/itns//etc/sdp.json,
Traceback (most recent call last):
  File "/opt/itns/lib/sdp.py", line 322, in upload
    response = urlopen(request).read()
  File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 502: Bad Gateway

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/itns/bin/itnsdispatcher", line 261, in <module>
    main(sys.argv[1:])
  File "/opt/itns/bin/itnsdispatcher", line 157, in main
    if (not s.upload(config.CONFIG)):
  File "/opt/itns/lib/sdp.py", line 336, in upload
    if not jsonErr or not self.handleSdpError(jsonErr):
  File "/opt/itns/lib/sdp.py", line 344, in handleSdpError
    if jsonErr and jsonErr['status']:
KeyError: 'status'
```

**Comment by ronnylov** [comment]
My sdp.json looks like this (edited out sensitive information)

```
{
   "protocolVersion": 1,
   "provider": {
      "certificates": [
         {
            "cn": "ignored",
            "content": "-----BEGIN CERTIFICATE-----xxxxxx----END CERTIFICATE-----",
            "id": 0
         }
      ],
      "id": "xxxxxxx",
      "name": "Lethernet.com",
      "nodeType": "residential",
      "terms": "You must follow the laws in the country of exit node location.",
      "wallet": "izxxxxxxxx...."   },
   "services": [
      {
         "allowRefunds": false,
         "certificates": [
            {
               "id": 0
            }
         ],
         "cost": "0.05000000",
         "disable": false,
         "downloadSpeed": 2000000,
         "firstPrePaidMinutes": 30,
         "firstVerificationsNeeded": 0,
         "id": "1A",
         "name": "Lethernet.com NL01",
         "proxy": [
            {
               "endpoint": "nl01.lethernet.com",
               "port": "8080/TCP"
            }
         ],
         "subsequentPrePaidMinutes": 60,
         "subsequentVerificationsNeeded": 0,
         "type": "proxy",
         "uploadSpeed": 2000000,
         "vpn": []
      }
   ]
}
```

**Comment by ronnylov** [comment]
Issue is solved together with ddvs.
The sdp.json file had probably some error on last upload.
Then when reuploading it did not work.

We changed provider-id and got no payment upload error.
Then changed back to correct payment id and got key error.
Then changed back to correct provider key and correct provider is and upload worked.
