### ISSUE TITLE
Error when starting lthnvpnd

### ISSUE THREAD

**Issue by ronnylov** [LetheanMovement/lethean-vpn#79]
Got problem now, can't start lthnvpnd any more on Lethernet FR.

```
lethe@fr01:~$ /opt/lthn/bin/lthnvpnd -l DEBUG
INFO:audit:type=SERVICE,action=START,obj=lthnvpnd,
DEBUG:lthnvpnd:Setting service 1A parameter backend_proxy_server to localhost:8881
DEBUG:lthnvpnd:Setting service 1A parameter uniqueid to default (abcd1234)
DEBUG:lthnvpnd:Setting service 1A parameter max_conns_per_period to default (10000)
DEBUG:lthnvpnd:Setting service 1A parameter max_requests_per_period to default (10000)
DEBUG:lthnvpnd:Setting service 1A parameter connect_timeout to default (5s)
DEBUG:lthnvpnd:Setting service 1A parameter status_port to default (8181)
DEBUG:lthnvpnd:Setting service 1A parameter dispatcher_http_host to default (127.0.0.1)
DEBUG:lthnvpnd:Setting service 1A parameter bind_addr to default (0.0.0.0)
DEBUG:lthnvpnd:Setting service 1A parameter max_connections to default (2000)
DEBUG:lthnvpnd:Setting service 1A parameter dispatcher_http_port to default (8188)
DEBUG:lthnvpnd:Setting service 1A parameter track_sessions to default (True)
DEBUG:lthnvpnd:Setting service 1A parameter conns_period to default (10s)
DEBUG:lthnvpnd:Setting service 1A parameter paymentid to default (authid1)
DEBUG:lthnvpnd:Setting service 1A parameter max_conns_per_ip to default (10000)
DEBUG:lthnvpnd:Setting service 1A parameter crt to /opt/lthn/etc/ca/certs/ha.cert.pem
DEBUG:lthnvpnd:Setting service 1A parameter key to /opt/lthn/etc/ca/private/ha.key.pem
DEBUG:lthnvpnd:Setting service 1A parameter timeout to default (30s)
DEBUG:lthnvpnd:Setting service 1A parameter name to FREEDOM
DEBUG:lthnvpnd:Setting service 1A parameter crtkey to /opt/lthn/etc/ca/certs/ha.both.pem
WARNING:lthnvpnd:Unknown parameter enabled for service 1A
DEBUG:lthnvpnd:Setting service 1B parameter backend_proxy_server to 127.0.0.1:8886
DEBUG:lthnvpnd:Setting service 1B parameter uniqueid to default (abcd1234)
DEBUG:lthnvpnd:Setting service 1B parameter max_conns_per_period to default (10000)
DEBUG:lthnvpnd:Setting service 1B parameter max_requests_per_period to default (10000)
DEBUG:lthnvpnd:Setting service 1B parameter connect_timeout to default (5s)
DEBUG:lthnvpnd:Setting service 1B parameter status_port to default (8181)
DEBUG:lthnvpnd:Setting service 1B parameter dispatcher_http_host to default (127.0.0.1)
DEBUG:lthnvpnd:Setting service 1B parameter bind_addr to default (0.0.0.0)
DEBUG:lthnvpnd:Setting service 1B parameter max_connections to default (2000)
DEBUG:lthnvpnd:Setting service 1B parameter dispatcher_http_port to default (8188)
DEBUG:lthnvpnd:Setting service 1B parameter track_sessions to default (True)
DEBUG:lthnvpnd:Setting service 1B parameter conns_period to default (10s)
DEBUG:lthnvpnd:Setting service 1B parameter paymentid to default (authid1)
DEBUG:lthnvpnd:Setting service 1B parameter max_conns_per_ip to default (10000)
DEBUG:lthnvpnd:Setting service 1B parameter crt to /opt/lthn/etc/ca/certs/ha.cert.pem
DEBUG:lthnvpnd:Setting service 1B parameter key to /opt/lthn/etc/ca/private/ha.key.pem
DEBUG:lthnvpnd:Setting service 1B parameter timeout to default (30s)
DEBUG:lthnvpnd:Setting service 1B parameter name to SAFE
DEBUG:lthnvpnd:Setting service 1B parameter crtkey to /opt/lthn/etc/ca/certs/ha.both.pem
WARNING:lthnvpnd:Unknown parameter enabled for service 1B
DEBUG:lthnvpnd:Setting service 1C parameter backend_proxy_server to 127.0.0.1:8888
DEBUG:lthnvpnd:Setting service 1C parameter uniqueid to default (abcd1234)
DEBUG:lthnvpnd:Setting service 1C parameter max_conns_per_period to default (10000)
DEBUG:lthnvpnd:Setting service 1C parameter max_requests_per_period to default (10000)
DEBUG:lthnvpnd:Setting service 1C parameter connect_timeout to default (5s)
DEBUG:lthnvpnd:Setting service 1C parameter status_port to default (8181)
DEBUG:lthnvpnd:Setting service 1C parameter dispatcher_http_host to default (127.0.0.1)
DEBUG:lthnvpnd:Setting service 1C parameter bind_addr to default (0.0.0.0)
DEBUG:lthnvpnd:Setting service 1C parameter max_connections to default (2000)
DEBUG:lthnvpnd:Setting service 1C parameter dispatcher_http_port to default (8188)
DEBUG:lthnvpnd:Setting service 1C parameter track_sessions to default (True)
DEBUG:lthnvpnd:Setting service 1C parameter conns_period to default (10s)
DEBUG:lthnvpnd:Setting service 1C parameter paymentid to default (authid1)
DEBUG:lthnvpnd:Setting service 1C parameter max_conns_per_ip to default (10000)
DEBUG:lthnvpnd:Setting service 1C parameter crt to /opt/lthn/etc/ca/certs/ha.cert.pem
DEBUG:lthnvpnd:Setting service 1C parameter key to /opt/lthn/etc/ca/private/ha.key.pem
DEBUG:lthnvpnd:Setting service 1C parameter timeout to default (30s)
DEBUG:lthnvpnd:Setting service 1C parameter name to SAFEST
DEBUG:lthnvpnd:Setting service 1C parameter crtkey to /opt/lthn/etc/ca/certs/ha.both.pem
WARNING:lthnvpnd:Unknown parameter enabled for service 1C
DEBUG:lthnvpnd:Setting service 1D parameter crt to /opt/lthn/etc/ca/certs/openvpn.cert.pem
DEBUG:lthnvpnd:Setting service 1D parameter ipmask to 255.255.0.0
DEBUG:lthnvpnd:Setting service 1D parameter key to /opt/lthn/etc/ca/private/openvpn.key.pem
DEBUG:lthnvpnd:Setting service 1D parameter mgmtport to 10111
DEBUG:lthnvpnd:Setting service 1D parameter tundev to tun0
DEBUG:lthnvpnd:Setting service 1D parameter dns to 172.28.0.11
DEBUG:lthnvpnd:Setting service 1D parameter iprange to 10.11.0.0
DEBUG:lthnvpnd:Setting service 1D parameter crtkey to /opt/lthn/etc/ca/certs/openvpn.both.pem
DEBUG:lthnvpnd:Setting service 1D parameter enabled to true
Traceback (most recent call last):
  File "/opt/lthn/bin/lthnvpnd", line 181, in <module>
    main(sys.argv[1:])
  File "/opt/lthn/bin/lthnvpnd", line 116, in main
    services.SERVICES.loadServer()
  File "/opt/lthn/lib/services.py", line 34, in loadServer
    if "enabled" not in cfg:
TypeError: argument of type 'NoneType' is not iterable

```

```
lethe@fr01:~$ cat /opt/lthn/etc/dispatcher.ini
[global]
;debug=DEBUG
ca=/opt/lthn/etc/ca/certs/ca.cert.pem
;provider-type=commercial
provider-id=befcf2ed**************************************************
provider-key=**********************************************************
provider-name=Lethernet FR
provider-terms=Sww https://lethernet.com
;provider-terms=@from_file.txt

;;; Wallet
wallet-address=iz5whrQx45AYP1QRW4ectT7Tfa9xBNdnSYrJJe4RNsLUUS34kBzqZAkjCKaegDX83g5P8uXGuMLay3HYRv4VpKex1jaGJdxLC
wallet-rpc-uri=http://127.0.0.1:14660/json_rpc
wallet-username=************
wallet-password=************

;;; SDP
;sdp-servers={sdpservers}

; Each service can be configured here. Key is service-id
[service-1A]
name=FREEDOM
backend_proxy_server=localhost:8881
crt=/opt/lthn/etc/ca/certs/ha.cert.pem
key=/opt/lthn/etc/ca/private/ha.key.pem
crtkey=/opt/lthn/etc/ca/certs/ha.both.pem

[service-1B]
name=SAFE
backend_proxy_server=127.0.0.1:8886
crt=/opt/lthn/etc/ca/certs/ha.cert.pem
key=/opt/lthn/etc/ca/private/ha.key.pem
crtkey=/opt/lthn/etc/ca/certs/ha.both.pem

[service-1C]
name=SAFEST
backend_proxy_server=127.0.0.1:8888
crt=/opt/lthn/etc/ca/certs/ha.cert.pem
key=/opt/lthn/etc/ca/private/ha.key.pem
crtkey=/opt/lthn/etc/ca/certs/ha.both.pem

[service-1D]
crt=/opt/lthn/etc/ca/certs/openvpn.cert.pem
key=/opt/lthn/etc/ca/private/openvpn.key.pem
crtkey=/opt/lthn/etc/ca/certs/openvpn.both.pem
enabled=true
mgmtport=10111
iprange=10.11.0.0
ipmask=255.255.0.0
dns=172.28.0.11
tundev=tun0

;[service-1B]
;crt=/opt/lthn/etc/ca/certs/openvpn.cert.pem
;key=/opt/lthn/etc/ca/private/openvpn.key.pem
;crtkey=/opt/lthn/etc/ca/certs/openvpn.both.pem
;reneg=600
;enabled=false
;iprange=1.2.3.0
;ipmask=255.255.0.0
;ip6range=fe80:abcd:1234::/64
;dns=127.0.0.1
;mgmtport=11123

; For client side scripts, service ids are prepended by 'C'
[service-C1A]
;http_proxy=127.0.0.1:3128
;endpoint=127.0.0.1
;port=1234
;proxy_port=8188
;proxy_bind=127.0.0.1
```

Only thing I did was adding the dns line. I can try to remove it.
No it made no difference.

**Comment by ronnylov** [comment]
I Think I found it!
I had set disabled=true in service 1E in sdp.json
Then I removed the section for service 1E in dispatcher.ini because "I disabled it"
But forgot to remove the diabled service 1E in sdp.json.

So if a service is disabled in sdp.json it still must be present in dispatcher.ini
That is how I interpret this.

So matching sdp.json with dispatcher.ini solved my problem.
